name: Flutter CI

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v1
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: flutter pub get
      - name: Format
        run: fluter format --set-exit-if-changed .
      - name: Analyze
        run: flutter analyze --fatal-infos --fatal-warnings .
      - name: Run tests
        run: flutter test --coverage
      - name: Check Code Coverage
        uses: ChicagoFlutter/lcov-cop@v1.0.0
        with:
          path: /coverage/lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}